package com.softdesign.devintensive.data.storage.models;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig respositoryDaoConfig;

    private final UserDao userDao;
    private final RespositoryDao respositoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        respositoryDaoConfig = daoConfigMap.get(RespositoryDao.class).clone();
        respositoryDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        respositoryDao = new RespositoryDao(respositoryDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Respository.class, respositoryDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        respositoryDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RespositoryDao getRespositoryDao() {
        return respositoryDao;
    }

}
