package com.softdesign.devintensive.data.storage.models;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.softdesign.devintensive.data.storage.models.Respository;
import com.softdesign.devintensive.data.storage.models.User;

import com.softdesign.devintensive.data.storage.models.RespositoryDao;
import com.softdesign.devintensive.data.storage.models.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig respositoryDaoConfig;
    private final DaoConfig userDaoConfig;

    private final RespositoryDao respositoryDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        respositoryDaoConfig = daoConfigMap.get(RespositoryDao.class).clone();
        respositoryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        respositoryDao = new RespositoryDao(respositoryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Respository.class, respositoryDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        respositoryDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public RespositoryDao getRespositoryDao() {
        return respositoryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
